import { Notification } from "./columns"

export const notifications: Notification[] = [
  {
    type: "Photo",
    space: "230 X 500 PX",
    country: "Saudi Arabia",
    city: "Riyadh",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Delivered",
  },
  {
    type: "Text",
    space: "PX 230 X 500",
    country: "United Arab Emirates",
    city: "Dubai",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "In Progress",
  },
  {
    type: "Text",
    space: "PX 230 X 500",
    country: "Kuwait",
    city: "Kuwait City",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Cancelled",
  },
  {
    type: "Photo",
    space: "PX 230 X 500",
    country: "Qatar",
    city: "Doha",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Delivered",
  },
  {
    type: "Text",
    space: "PX 230 X 500",
    country: "Bahrain",
    city: "Manama",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "In Progress",
  },
  {
    type: "Photo",
    space: "230 X 500 PX",
    country: "Oman",
    city: "Muscat",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Delivered",
  },
  {
    type: "Text",
    space: "PX 230 X 500",
    country: "Egypt",
    city: "Cairo",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "In Progress",
  },
  {
    type: "Photo",
    space: "230 X 500 PX",
    country: "Jordan",
    city: "Amman",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Cancelled",
  },
  {
    type: "Text",
    space: "PX 230 X 500",
    country: "Lebanon",
    city: "Beirut",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "Delivered",
  },
  {
    type: "Photo",
    space: "230 X 500 PX",
    country: "Iraq",
    city: "Baghdad",
    dateTime: "14, Jan, 2025 - 11:08 PM",
    status: "In Progress",
  },
] 